stages:
  data_acquisition:
    cmd: jupyter nbconvert --execute --inplace notebooks/01_data_acquisition.ipynb
    deps:
      - notebooks/01_data_acquisition.ipynb
    outs:
      - Data/raw

  exploratory_data_analysis:
    cmd: jupyter nbconvert --execute --inplace notebooks/02_exploratory_data_analysis.ipynb
    deps:
      - Data/raw
      - notebooks/02_exploratory_data_analysis.ipynb

  preprocessing:
    cmd: jupyter nbconvert --execute --inplace notebooks/03_data_preprocessing.ipynb
    deps:
      - Data/raw
      - notebooks/03_data_preprocessing.ipynb
    outs:
      - Data/processed

  train_test_split:
    cmd: jupyter nbconvert --execute --inplace notebooks/04_train_test_split.ipynb
    deps:
      - Data/processed
      - notebooks/04_train_test_split.ipynb
    outs:
      - Data/split

  imbalance_handling:
    cmd: jupyter nbconvert --execute --inplace notebooks/05_multilabel_imbalance_handling.ipynb
    deps:
      - Data/split
      - notebooks/05_multilabel_imbalance_handling.ipynb

  final_model_training:
    cmd: jupyter nbconvert --execute --inplace notebooks/11_final_model.ipynb
    deps:
      - Data/split
      - notebooks/05_multilabel_imbalance_handling.ipynb
      - notebooks/11_final_model.ipynb
    outs:
      - models/multilabel_xgboost_classifier_chain.pkl
      - models/best_xgb_params.json
      - models/optimal_thresholds.json

  shap_explainability:
    cmd: jupyter nbconvert --execute --inplace notebooks/10_shap_explainability.ipynb
    deps:
      - models/multilabel_xgboost_classifier_chain.pkl
      - notebooks/10_shap_explainability.ipynb