stages:
  data_acquisition:
    cmd: python src/01_data_acquisition.py
    deps:
      - src/01_data_acquisition.py
    outs:
      - Data/raw

  preprocessing:
    cmd: python src/03_data_preprocessing.py
    deps:
      - Data/raw/Dataset.csv
      - src/03_data_preprocessing.py
    outs:
      - Data/processed/cleaned_data.csv

  train_test_split:
    cmd: python src/04_train_test_split.py
    deps:
      - Data/processed/cleaned_data.csv
      - src/04_train_test_split.py
    outs:
      - Data/split/train_data.csv
      - Data/split/test_data.csv

  imbalance_handling:
    cmd: python src/05_multilabel_imbalance_handling.py
    deps:
      - Data/split/train_data.csv
      - src/05_multilabel_imbalance_handling.py
    outs:
      - Data/processed/train_smote.csv

  hyperparameter_tuning_xgb_br:
    cmd: python src/06_hyperparameter_tuning_xgb_br.py
    deps:
      - Data/processed/train_smote.csv
      - src/06_hyperparameter_tuning_xgb_br.py
    outs:
      - models/best_xgb_params_br.json

  hyperparameter_tuning_xgb_cc:
    cmd: python src/06_hyperparameter_tuning_xgb_cc.py
    deps:
      - Data/processed/train_smote.csv
      - src/06_hyperparameter_tuning_xgb_cc.py
    outs:
      - models/best_xgb_params_cc.json

  baseline_randomforest:
    cmd: python src/07a_baseline_randomforest_br.py
    deps:
      - Data/processed/train_smote.csv
      - Data/split/test_data.csv
      - src/07a_baseline_randomforest_br.py

  baseline_svm:
    cmd: python src/07b_baseline_svm_br.py
    deps:
      - Data/processed/train_smote.csv
      - Data/split/test_data.csv
      - src/07b_baseline_svm_br.py

  xgboost_binary_relevance:
    cmd: python src/08_baseline_xgboost_br.py
    deps:
      - Data/processed/train_smote.csv
      - Data/split/test_data.csv
      - models/best_xgb_params_br.json
      - src/08_baseline_xgboost_br.py

  xgboost_classifier_chain:
    cmd: python src/08_xgboost_classifierchain.py
    deps:
      - Data/processed/train_smote.csv
      - Data/split/test_data.csv
      - models/best_xgb_params_cc.json
      - src/08_xgboost_classifierchain.py

  shap_explainability:
    cmd: python src/09_shap_explainability.py
    deps:
      - Data/split/test_data.csv
      - models/multilabel_xgboost_classifier_chain.pkl
      - src/09_shap_explainability.py