stages:
  data_acquisition:
    cmd: python src/01_data_acquisition.py
    deps:
      - src/01_data_acquisition.py
    outs:
      - Data/raw

  exploratory_data_analysis:
    cmd: python src/02_exploratory_data_analysis.py
    deps:
      - Data/raw
      - src/02_exploratory_data_analysis.py

  preprocessing:
    cmd: python src/03_data_preprocessing.py
    deps:
      - Data/raw
      - src/03_data_preprocessing.py
    outs:
      - Data/processed

  train_test_split:
    cmd: python src/04_train_test_split.py
    deps:
      - Data/processed
      - src/04_train_test_split.py
    outs:
      - Data/split

  imbalance_handling:
    cmd: python src/05_multilabel_imbalance_handling.py
    deps:
      - Data/split
      - src/05_multilabel_imbalance_handling.py

  final_model_training:
    cmd: python src/11_final_model.py
    deps:
      - Data/split
      - src/05_multilabel_imbalance_handling.py
      - src/11_final_model.py
    outs:
      - models/multilabel_xgboost_classifier_chain.pkl
      - models/best_xgb_params.json
      - models/optimal_thresholds.json

  shap_explainability:
    cmd: python src/10_shap_explainability.py
    deps:
      - models/multilabel_xgboost_classifier_chain.pkl
      - src/10_shap_explainability.py